# The global setting will take effect for all hosts,
#   if he does not set the corresponding value
# The 'global' is not necessary
global:
  # If 'global.port' is not set, the default port is 22
  port: 23
  # If 'global.port' is not set, the default username is root
  username: root
  # The 'global.password' have not default value, 
  #   please set 'global.password' or set 'password' for each host
  password: cm9vdCQxMjM=
  # The 'global.labels' will add for all hosts
  # All host always have label all=all,
  #   and you can override all=all by setting 'global.labels'
  labels: 
    # all: all
    app: my_host
groups:
  # Execute command 'ls -l /' for mysql_master 
  #   gopssh execute -h mysql_master 'ls -l /'
  mysql_master:
    # The 'hosts.<host_alias>.ips' is necessary
    ips: 
    - 172.16.8.83
    # Overwrite 'global.port' 23
    port: 30
    # * Overwrite 'global.username' root
    username: mysql
    # Overwrite 'global.password' cm9vdCQxMjM=
    # Please enter user password with base64
    #   Encode password with base64 with command:
    #     echo -n 'mysql$123' | base64
    #     gopssh base64 'mysql$123'
    #   Decode base64 password with command:
    #     echo -n 'bXlzcWwkMTIz' | base64 -d
    #     gopssh base64 -d 'bXlzcWwkMTIz'
    password: bXlzcWwkMTIz
    labels:
      # Execute command 'ls -l /' for all host that have label app=mysql
      #   gopssh execute -l app=mysql 'ls -l /'
      app: mysql
      mysql: master
      # app: my_host
  # The sample without comment
  mysql_slaves:
    ip: 
    - 172.16.8.84
    - 172.16.8.85
    port: 22
    username: mysql
    password: bXlzcWwkMTIz
    labels:
      app: mysql
      mysql: slave
  # The sample with 'global'
  nginx:
    ip: 
    - 172.16.8.87
    # port: 23
    # username: root
    # password: cm9vdCQxMjM=
    # labels:
    #   all: all