hosts:
  mysql_master:
    ip: 172.16.8.83
    # username: root
    password: cm9vdCQxMjM= # echo -n 'root$123' | base64
    # labels:
    #   all: all
 mysql_slaves:
    ip: 172.16.8.[84:86]
    username: mysql
    password: bXlzcWwkMTIz # echo -n 'bXlzcWwkMTIz' | base64 -d
    labels:
      mysql: slave
    # all: all
