groups:
  - ips: 
    - 172.16.8.83
    # username: root
    # port: 22
    password: cm9vdCQxMjM= # echo -n 'root$123' | base64
  - ips: 
    - 172.16.8.84
    - 172.16.8.85
    - 172.16.8.86
    username: mysql
    # port: 22
    password: bXlzcWwkMTIz # echo -n 'bXlzcWwkMTIz' | base64 -d
    labels:
      mysql: slave
